port: PORT
enableIpv6: ENABLE_IPV6
interface: INTERFACE
mdnsInterfaces:
  __name: MDNS_INTERFACES
  __format: yaml
sendersBlacklist:
  __name: SENDERS_BLACKLIST
  __format: yaml
serviceWhitelist:
  __name: SERVICE_WHITELIST
  __format: yaml
remote: REMOTE
