port: 42069
enableIpv6: true

# THIS IS WHERE SERVER WILL LISTEN ON HTTP CONNECTIONS
interface:
  - 0.0.0.0

# UNCOMMENT TO LISTEN FOR MDNS PACKETS ONLY ON SPECIFIC INTERFACES:
#mdnsInterfaces:
#  - en0

sendersBlacklist:
  - '127.0.0.1'

serviceWhitelist:
  - '_homekit._tcp.local'
  - '_hap._tcp.local'

# UNCOMMENT THIS TO START AS A CLIENT:
# remote: 192.168.1.10
